-- 1. Create Orders Table
create table if not exists orders (
    id bigint generated by default as identity primary key,
    phone text not null,
    total_amount numeric not null,
    status text not null default 'pending', -- pending, confirmed, paid, completed, cancelled
    created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. Create Order Items Table
create table if not exists order_items (
    id bigint generated by default as identity primary key,
    order_id bigint references orders(id) on delete cascade,
    product_name text not null,
    quantity int not null default 1,
    unit_price numeric not null,
    options jsonb default '{}'::jsonb, -- Stores the JSON structure of selected ingredients
    created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 3. Security (RLS)
alter table orders enable row level security;
alter table order_items enable row level security;

create policy "Service role manages orders" 
    on orders 
    for all 
    using (true) 
    with check (true);

create policy "Service role manages items" 
    on order_items 
    for all 
    using (true) 
    with check (true);
