-- 1. Crear tabla categories si no existe
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL
);

-- 2. Habilitar seguridad (opcional pero recomendado)
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read access" ON categories FOR SELECT USING (true);

-- 3. MIGRACION INTELIGENTE: Si existe la columna 'category' (texto) antigua, mover datos
DO $$
BEGIN
    -- Si existe la columna antigua 'category'
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'products' AND column_name = 'category') THEN
        -- Insertar categorias únicas encontradas en los productos existentes
        INSERT INTO categories (name, slug)
        SELECT DISTINCT category, lower(regexp_replace(category, '[^a-zA-Z0-9]+', '-', 'g'))
        FROM products
        WHERE category IS NOT NULL AND category != ''
        ON CONFLICT (slug) DO NOTHING;
    END IF;
END $$;

-- 4. Asegurar categorías base requeridas por el Bot
INSERT INTO categories (name, slug) VALUES 
('Pokes Clásicos', 'pokes'),
('Sushi Burgers', 'burgers'),
('Entradas', 'entradas'),
('Bebidas', 'bebidas')
ON CONFLICT (slug) DO NOTHING;

-- 5. Agregar columna category_id a products
ALTER TABLE products ADD COLUMN IF NOT EXISTS category_id BIGINT REFERENCES categories(id);

-- 6. VINCULAR DATA: Conectar productos con sus categorías
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'products' AND column_name = 'category') THEN
        UPDATE products p
        SET category_id = c.id
        FROM categories c
        WHERE lower(p.category) = lower(c.name)
        AND p.category_id IS NULL;
    END IF;
END $$;

-- 7. Fallback: Vincular por nombre del producto si falló lo anterior
UPDATE products SET category_id = (SELECT id FROM categories WHERE slug = 'pokes') 
WHERE category_id IS NULL AND (name ILIKE '%poke%' OR name ILIKE '%bowl%');

UPDATE products SET category_id = (SELECT id FROM categories WHERE slug = 'burgers') 
WHERE category_id IS NULL AND (name ILIKE '%burger%' OR name ILIKE '%hamburguesa%');

-- 8. Limpiar: Cualquier otro producto sin categoría va a "Entradas" por defecto (opcional)
-- UPDATE products SET category_id = (SELECT id FROM categories WHERE slug = 'entradas') WHERE category_id IS NULL;
