-- 1. Create Categories Table
CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Insert Default Categories
INSERT INTO categories (name, slug) VALUES 
('Pokes Clásicos', 'pokes'),
('Sushi Burgers', 'burgers'),
('Entradas', 'entradas'),
('Bebidas', 'bebidas')
ON CONFLICT (slug) DO NOTHING;

-- 3. Update Products Table to link to Categories
ALTER TABLE products ADD COLUMN IF NOT EXISTS category_id BIGINT REFERENCES categories(id);

-- 4. Link existing products to categories
-- Default all to Pokes first
UPDATE products SET category_id = (SELECT id FROM categories WHERE slug = 'pokes') WHERE category_id IS NULL;

-- Update Burgers
UPDATE products 
SET category_id = (SELECT id FROM categories WHERE slug = 'burgers') 
WHERE name ILIKE '%burger%' OR name ILIKE '%hamburguesa%';

-- Enable RLS (Optional but good practice)
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON categories
    FOR SELECT USING (true);
