-- 1. Backup existing tables (optional, for safety)
CREATE TABLE IF NOT EXISTS old_sizes AS SELECT * FROM sizes;
CREATE TABLE IF NOT EXISTS old_ingredients AS SELECT * FROM ingredients;

-- 2. Drop old tables (or clean them if we want to reuse names, but better to start fresh)
DROP TABLE IF EXISTS step_options CASCADE;
DROP TABLE IF EXISTS product_steps CASCADE;
DROP TABLE IF EXISTS products CASCADE;

-- 3. Create 'products' table
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    base_price NUMERIC NOT NULL DEFAULT 0,
    type TEXT NOT NULL CHECK (type IN ('poke', 'burger', 'other')),
    slug TEXT UNIQUE NOT NULL, -- for url identification
    image_url TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Create 'product_steps' table (The "Categories" of a product)
CREATE TABLE product_steps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    name TEXT NOT NULL, -- Internal ID: 'base', 'protein'
    label TEXT NOT NULL, -- Display: 'Elige tu Base'
    "order" INTEGER NOT NULL DEFAULT 0,
    min_selections INTEGER NOT NULL DEFAULT 0, -- 0 = optional
    max_selections INTEGER, -- NULL = unlimited
    price_per_extra NUMERIC DEFAULT 0, -- Cost if user exceeds 'included' (logic handled in FE usually, or strictly here)
    is_active BOOLEAN DEFAULT true
);

-- 5. Create 'step_options' table (The "Ingredients" in a step)
CREATE TABLE step_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    step_id BIGINT REFERENCES product_steps(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    price_extra NUMERIC DEFAULT 0, -- Markup for specific premium ingredients
    is_available BOOLEAN DEFAULT true,
    image_url TEXT,
    "order" INTEGER DEFAULT 0
);

-- =============================================
-- SEED DATA (Based on User's Menu Image)
-- =============================================

-- A. Insert Products
INSERT INTO products (name, slug, type, base_price, description, image_url) VALUES 
('Poke Mediano', 'poke-mediano', 'poke', 145, '1 Proteína, 3 Toppings, 2 Crunchys, 1 Salsa', 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c'),
('Poke Grande', 'poke-grande', 'poke', 165, '2 Proteínas, 4 Toppings, 2 Crunchys, 2 Salsas', 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd');

-- B. Insert Steps for Poke Mediano (ID: 1)
-- Structure: Base (1-2), Prote (1), Toppings (3), Crunch (2), Salsas (1)
INSERT INTO product_steps (product_id, name, label, "order", min_selections, max_selections, price_per_extra) VALUES
(1, 'base', 'Base (Elige una mezcla o dos)', 1, 1, 2, 0),
(1, 'protein', 'Proteína (Elige 1)', 2, 1, 1, 40),
(1, 'toppings', 'Toppings (Elige 3)', 3, 0, 3, 25),
(1, 'crunch', 'Crunch (Elige 2)', 4, 0, 2, 15),
(1, 'sauces', 'Salsas (Elige 1)', 5, 0, 1, 15);

-- C. Insert Steps for Poke Grande (ID: 2)
-- Structure: Base (1-2), Prote (2), Toppings (4), Crunch (2), Salsas (2)
INSERT INTO product_steps (product_id, name, label, "order", min_selections, max_selections, price_per_extra) VALUES
(2, 'base', 'Base (Elige una mezcla o dos)', 1, 1, 2, 0),
(2, 'protein', 'Proteína (Elige 2)', 2, 1, 2, 40),
(2, 'toppings', 'Toppings (Elige 4)', 3, 0, 4, 25),
(2, 'crunch', 'Crunch (Elige 2)', 4, 0, 2, 15),
(2, 'sauces', 'Salsas (Elige 2)', 5, 0, 2, 15);

-- D. Insert Options (Ingredients)
-- We need to insert these into the steps we just created. 
-- Since IDs are dynamic, we'll use a DO block or just assume serial IDs 1-10 for simplicity in this script, 
-- but for robustness, let's use a Common Table Expression setup if supported, or just separate manual inserts.
-- Given Supabase SQL Editor support, simple INSERTs are safer. 
-- We know:
-- Mediano Steps: 1..5
-- Grande Steps: 6..10
-- (This relies on clean tables and serial starting at 1. If run multiple times, IDs shift. BUT we drop tables above so it resets.)

-- --- BASES (Step 1 & 6) ---
INSERT INTO step_options (step_id, name) VALUES
(1, 'Arroz Blanco'), (1, 'Arroz Negro'), (1, 'Noodles de Vegetal'), (1, 'Lechuga (Mix)'),
(6, 'Arroz Blanco'), (6, 'Arroz Negro'), (6, 'Noodles de Vegetal'), (6, 'Lechuga (Mix)');

-- --- PROTEINS (Step 2 & 7) ---
-- "Agrega extra por $40" is handled by step `price_per_extra`.
-- Specific premiums like Philadelphia or Avocado might need price_extra here if they were proteins, but they are toppings.
INSERT INTO step_options (step_id, name) VALUES
(2, 'Atún Fresco'), (2, 'Spicy Tuna'), (2, 'Arrachera'), (2, 'Pollo al Grill'), (2, 'Pollo Teriyaki'), (2, 'Sweet Salmon'), (2, 'Kanikama'),
(7, 'Atún Fresco'), (7, 'Spicy Tuna'), (7, 'Arrachera'), (7, 'Pollo al Grill'), (7, 'Pollo Teriyaki'), (7, 'Sweet Salmon'), (7, 'Kanikama');

-- --- TOPPINGS (Step 3 & 8) ---
-- Menu says "Agrega extra por $25".
-- Some items have stars (Aguacate, Queso Phila). Assuming typical "Premiums" might check with user, but let's add them standard for now or assume they are the standard list.
-- Actually, usually Avocado is premium. Let's add a small premium just in case, or keep 0 if fits in "Included".
-- The menu says "Agrega extra por $25", implies that's for the 4th, 5th topping etc. 
-- BUT "Queso Philadelphia" has a Star. "Aguacate" has a Star. 
-- Often stars mean "Extra Cost" even if included? Or just "Recommended"?
-- "Recomendación / Saludable" key is at the bottom.
-- Star = Recomendación. Leaf = Saludable.
-- So NO extra price inside the limit.
INSERT INTO step_options (step_id, name) VALUES
(3, 'Pepino'), (3, 'Aguacate'), (3, 'Mango'), (3, 'Zanahoria'), (3, 'Elotes'), (3, 'Pimiento'), (3, 'Edamames'), (3, 'Tomate Cherry'), (3, 'Queso Philadelphia'),
(8, 'Pepino'), (8, 'Aguacate'), (8, 'Mango'), (8, 'Zanahoria'), (8, 'Elotes'), (8, 'Pimiento'), (8, 'Edamames'), (8, 'Tomate Cherry'), (8, 'Queso Philadelphia');

-- --- CRUNCH (Step 4 & 9) ---
-- "Agrega extra por $15"
INSERT INTO step_options (step_id, name) VALUES
(4, 'Almendra Fileteada'), (4, 'Won Ton'), (4, 'Cacahuate Garapiñado'), (4, 'Cacahuate'), (4, 'Banana Chips'), (4, 'Betabel Bacon'), (4, 'Maicito Enchilado'), (4, 'Maicito'),
(9, 'Almendra Fileteada'), (9, 'Won Ton'), (9, 'Cacahuate Garapiñado'), (9, 'Cacahuate'), (9, 'Banana Chips'), (9, 'Betabel Bacon'), (9, 'Maicito Enchilado'), (9, 'Maicito');

-- --- SALSAS (Step 5 & 10) ---
-- "Agrega extra por $15"
INSERT INTO step_options (step_id, name) VALUES
(5, 'Soya'), (5, 'Siracha'), (5, 'Ponzu'), (5, 'Mango Habanero'), (5, 'Mayo Ajo'), (5, 'Mayo Cilantro'), (5, 'Anguila'), (5, 'Olive Oil'), (5, 'Habanero Drops'), (5, 'Cacahuate'), (5, 'Agridulce'),
(10, 'Soya'), (10, 'Siracha'), (10, 'Ponzu'), (10, 'Mango Habanero'), (10, 'Mayo Ajo'), (10, 'Mayo Cilantro'), (10, 'Anguila'), (10, 'Olive Oil'), (10, 'Habanero Drops'), (10, 'Cacahuate'), (10, 'Agridulce');

-- =============================================
-- GRANT PERMISSIONS (Fixes potential RLS issues for public)
-- =============================================
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_steps ENABLE ROW LEVEL SECURITY;
ALTER TABLE step_options ENABLE ROW LEVEL SECURITY;

-- Allow public read access
CREATE POLICY "Public products read" ON products FOR SELECT USING (true);
CREATE POLICY "Public steps read" ON product_steps FOR SELECT USING (true);
CREATE POLICY "Public options read" ON step_options FOR SELECT USING (true);

-- Allow authenticated (admin) write access
CREATE POLICY "Admin products write" ON products FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin steps write" ON product_steps FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin options write" ON step_options FOR ALL USING (auth.role() = 'authenticated');
